-- ============================================================
-- Mock data: 30 CinemaRooms them cho man Quan ly Phong chieu
-- Chay sau create_database.sql. Tranh trung ten voi cac phong da co
-- san (vd: "Phong 1", "Phong 3", "Phong 10", "Phong IMAX" trong seed
-- goc hoac da tao qua UI) vi room_name co UNIQUE constraint.
-- ============================================================
USE MovieTicketDB;
GO

INSERT INTO CinemaRooms (id, room_name, capacity, status, created_at) VALUES
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC04', N'Phòng 2',          100, 'ACTIVE',   DATEADD(DAY, -90, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC05', N'Phòng 4',           90, 'ACTIVE',   DATEADD(DAY, -88, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC06', N'Phòng 5',           90, 'ACTIVE',   DATEADD(DAY, -88, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC07', N'Phòng 6',           75, 'ACTIVE',   DATEADD(DAY, -85, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC08', N'Phòng 7',           75, 'INACTIVE', DATEADD(DAY, -85, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC09', N'Phòng 8',          110, 'ACTIVE',   DATEADD(DAY, -80, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC10', N'Phòng 9',          110, 'ACTIVE',   DATEADD(DAY, -80, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC11', N'Phòng 11',          60, 'ACTIVE',   DATEADD(DAY, -70, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC12', N'Phòng 12',          60, 'INACTIVE', DATEADD(DAY, -70, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC13', N'Phòng 13',          65, 'ACTIVE',   DATEADD(DAY, -65, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC14', N'Phòng 14',          65, 'ACTIVE',   DATEADD(DAY, -65, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC15', N'Phòng 15',          80, 'ACTIVE',   DATEADD(DAY, -60, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC16', N'Phòng 16',          80, 'ACTIVE',   DATEADD(DAY, -60, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC17', N'Phòng 17',          70, 'INACTIVE', DATEADD(DAY, -55, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC18', N'Phòng 18',          70, 'ACTIVE',   DATEADD(DAY, -55, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC19', N'Phòng 19',          95, 'ACTIVE',   DATEADD(DAY, -50, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC20', N'Phòng 20',          95, 'ACTIVE',   DATEADD(DAY, -50, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC21', N'Phòng 21',         100, 'ACTIVE',   DATEADD(DAY, -45, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC22', N'Phòng 22',         100, 'INACTIVE', DATEADD(DAY, -45, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC23', N'Phòng 23',          55, 'ACTIVE',   DATEADD(DAY, -40, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC24', N'Phòng 24',          55, 'ACTIVE',   DATEADD(DAY, -40, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC25', N'Phòng 25',          85, 'ACTIVE',   DATEADD(DAY, -35, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC26', N'Phòng 26',          85, 'ACTIVE',   DATEADD(DAY, -35, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC27', N'Phòng 27',          40, 'INACTIVE', DATEADD(DAY, -30, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC28', N'Phòng 28',          40, 'ACTIVE',   DATEADD(DAY, -30, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC29', N'Phòng IMAX 2',      85, 'ACTIVE',   DATEADD(DAY, -20, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC30', N'Phòng 4DX',         60, 'ACTIVE',   DATEADD(DAY, -18, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC31', N'Phòng Premium 1',   50, 'ACTIVE',   DATEADD(DAY, -10, GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC32', N'Phòng Sweetbox',    30, 'ACTIVE',   DATEADD(DAY, -5,  GETDATE())),
('CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCC33', N'Phòng VIP 1',       45, 'ACTIVE',   DATEADD(DAY, -2,  GETDATE()));
GO
